services:
  web:
    build: .
    container_name: BiblioTech-PHP
    ports:
      - "${PORT_PHP}:80"
    environment:
      - DB_NAME=${DB}
      - DB_USER=${USER}
      - DB_PASS=${PASSWORD}
      - DB_HOST=db
    volumes:
      - ./src:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: BiblioTech-DB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPWD}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit
    container_name: BiblioTech-Mail
    ports:
      - "8025:8025" # Interfaccia Web per vedere le email
      - "1025:1025" # Porta SMTP per invio email
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: admin-panel
    ports:
      - "${PORT_ADMIN}:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${ROOTPWD}
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge